### ISSUE TITLE
[BUG] Tier 73 BattlePass Boots

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#101]
**Describe the bug**
Claiming Tier 73 BattlePass Boots does not reward the item.

**To Reproduce**
1. Reach tier 73 in /bp
2. Claim the BattlePass Boots

**Expected behavior**
Receive the BattlePass Boots after claiming.

**Screenshots**
![2022-08-06_11 32 46](https://user-images.githubusercontent.com/29812480/183261727-e9cc7451-8f00-4581-8bd4-c2d6e0dc7cb7.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
Who would have thought...another capitalization issue....fixed! 

Glad you are the first one to unlock all of the BP items lol
