### ISSUE TITLE
[FEATURE] /plot merge

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#102]
**Please describe the feature you think should be implented**
could /plot merge be enabled in creative, this shows when i try with my plots that are next to eachover
![image](https://user-images.githubusercontent.com/42377455/183308243-4a3b46d5-87c3-4976-b11e-be8ccda88a43.png)

**Comment by ImSnipper** [comment]
@GorilloYT What are your thoughts on this feature? Perhaps we can give it to donors, or it can be purchased in the upgrade shop with coins?

**Comment by ImSnipper** [comment]
This feature has been added for Lord+ on Creative.

**Comment by HagridHills** [comment]
when i type the command, it still shows this 
![image](https://user-images.githubusercontent.com/42377455/186027785-1d9e166f-0c0d-42d4-bb28-c01ca7b90d67.png)
