### ISSUE TITLE
[BUG] Bat Blaster And Other Gadgets

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#105]
**Describe the bug**
The Bat Blaster gadget is not in the gadget list in the Survival server.

**To Reproduce**
1. See the Bat Blaster gadget in the /hub
2. Use /Survival
3. Use /cosmetics to see the Bat Blaster is not listed.

**Expected behavior**
The ability to blast bats at my teammates.

**Screenshots**
![image](https://user-images.githubusercontent.com/29812480/183664236-b3a79c6a-f76f-4893-bc34-1e2204244a8f.png)
![image](https://user-images.githubusercontent.com/29812480/183664363-247bfead-4a50-4d99-952f-7585d7940a05.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
I also found that the following gadgets are listed in the /hub, but not in /survival:

Ethereal Pearl
TNT
Paintball
Rocket
Grappling Hook
Bombman
Flesh Hook
Wither Missile

**Comment by ItsMeGriff** [comment]
I *think* gadgets are disabled in survival need @ImSnipper to confirm.

**Comment by MelodyMcKenna** [comment]
Sorry I didn't specify the screenshots. The top is in the /hub, and the bottom is in /survival. The ones I have unlocked and available in /survival do work; however, now I'm unsure if they're supposed to.

**Comment by ImSnipper** [comment]
Yep, Griff is right. We did initially disable some gadgets on Survival. However, now that we've limited the gadgets to ONLY the spawn region, I don't see an issue with reenabling those cosmetics. I will enable them again this weekend!
