### ISSUE TITLE
[BUG] World Guard chat spam

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#106]
After using the world guard yesterday each time world edit is used your chat gets filled with tons of text to the point you cannot read anything but world edit info. 

**To Reproduce**
Use world edit 

**Expected behavior**
Beforehand it was only 1-3 lines of text but now it's 20+ lines of text 

**Screenshots**

![2022-08-10_11 48 21](https://user-images.githubusercontent.com/109323715/183954525-0aef0bb8-5c71-44da-9b29-78fcdfd03866.png)

![2022-08-10_11 48 18](https://user-images.githubusercontent.com/109323715/183954566-58b4ade1-e971-407f-afe3-28eb0f1e57e9.png)

All of this is from just one command with world edit, could it be done so little to no messages pop up when using world edit ?

**Comment by ImSnipper** [comment]
Fixed!
