### ISSUE TITLE
[BUG] Potion Duration

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#109]
**Describe the bug**
The potion duration bonus from the skills system is inconsistent. My shop sells potions with a 33-second bonus duration from my skill level, but when I logged on today and brewed some potions at a new location to restock, they had a 14-second bonus. I placed a new brewing stand and used the same ingredients to make night vision potions, and they had an extra 33 seconds again.

**To Reproduce**
1. Unknown

**Expected behavior**
Bonus times are consistent with the player's Alchemy /skills regardless of the brewing stand used.

**Screenshots**
![2022-08-14_13 12 17](https://user-images.githubusercontent.com/29812480/184553633-c085984f-df7c-4b30-ad4f-d22f7c8c2e2e.png)
![2022-08-14_13 12 45](https://user-images.githubusercontent.com/29812480/184553635-b88af0a1-cde2-4dd9-85b4-89ce53e1164f.png)
![2022-08-14_13 23 19](https://user-images.githubusercontent.com/29812480/184553645-c7cd8d61-bf23-4691-8162-81b9b2a046fe.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by ImSnipper** [comment]
According to Giz, "Might be an issue with what gear is equipped, or what bonuses are on their account at the time from the skills"

He is going to look into the issue tonight though. Thought I would give you his thoughts though, incase that might lead you to a solution.

**Comment by ImSnipper** [comment]
@MelodyMcKenna did Giz's idea assist at all with coming to a solution on this problem?

**Comment by MelodyMcKenna** [comment]
@ImSnipper, I've tried to replicate the problem unsuccessfully a few times. I don't know what caused it, but I'll keep an eye out to see if it happens again. Thanks for taking the time to look into this.

**Comment by ImSnipper** [comment]
Thank you for the update! I am going to close this issue, but if it comes up again, feel free to reopen!
