### ISSUE TITLE
[FEATURE] Enable the death effects in PVP arena.

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#11]
All cosmetics are disabled in the PVP arena, but it would be cool to enable the use of death effects if possible.

**Comment by ItsMeGriff** [comment]
Should be possible by setting “death-effects: false” in the world guard region file for the pvp arena. 
![Uploading 3AC52219-31B0-4354-BFF7-7AE9C85797C4.png…]()

**Comment by ItsMeGriff** [comment]
I really like this idea but currently not able todo with the current implementation of Worldguard support and pro cosmetics will need to readdress this later.
