### ISSUE TITLE
[BUG] Deathchest hologram stuck

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#110]
**Describe the bug**
The hologram for 2 deathchests are stuck and the timers won't work. The deathchest was found after the 15minutes so just the hologram needs to be removed. Possibly finding out how this happened to prevent it in the future would be good. 

**To Reproduce**
/tp 1766 100 311

**Screenshots**
![image](https://user-images.githubusercontent.com/109323715/184679641-d4567d7b-795b-463c-86d2-ba9bfac0d855.png)

The user who died says they were also kicked from the server for the 24hr restart and when rejoining they were dead so possibly a mob killed them and they never found the chest?

**Comment by ImSnipper** [comment]
Are these holograms still stuck there? I think the server restart may have gotten rid of them. Please let me know. Ty

**Comment by ImSnipper** [comment]
Fixed!
