### ISSUE TITLE
survival simulation and render

### ISSUE THREAD

**Issue by apexmag** [GorilloCraft/Server#111]
was looking to possibly extend the simulation and render distance, even if just in the survival server.
the render is less of the issue in my opinion in comparison to the simulation distance. the current settings make it very difficult to build certain survival farms and like builds. 

as of now i have done a few tests in game and the standard mob spawn is at 24 blocks from player center but the despawn radius is only around 45-48. so roughly 20 blocks to be able to build a working farm in at the moment. ive built many farms in different areas of the server and they all match up to these numbers for the most part.

at the 45 block radius mark you might get a mob spawn in but it wont move until you get within around 25-26 blocks of it, which makes a very difficult afk area possible do to the range of 24-25 spawn in radius.

i feel the simulation distance wouldnt be to harmful to any lag issues across the server especially if the render distance stays on the lower side then the sim distance.
.

**Comment by ImSnipper** [comment]
@ItsMeGriff I think it would be fine to increase the simulation distance. What do you think?

**Comment by ImSnipper** [comment]
I have increased the simulation distance to the default Minecraft value (10 Chunks) which is the same as the current view distance. Hopefully this helps!

**Comment by ImSnipper** [comment]
BTW this change will take effect at the daily restart.
