### ISSUE TITLE
[BUG] Tier 75 Chat Tag

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#112]
**Describe the bug**
The free chat tag for reaching tier 75 in the BattlePass does not display in /tags after being claimed. 

**To Reproduce**
1. Reach tier 75 in /bp
2. Claim the tag
3. Use /tags

**Expected behavior**
The Chat Tag is available in /tags after being claimed in /bp

**Screenshots**
![2022-08-16_18 41 05](https://user-images.githubusercontent.com/29812480/185016036-4975d150-75ef-4d72-976c-456bb7e52493.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
The Enchanted Golden Apple for tier 75 is awarded as intended.

**Comment by MelodyMcKenna** [comment]
The user Angelay15 reported this to the staff team. Please let us know if they need to claim it again or have it manually given to them.

**Comment by ImSnipper** [comment]
Thanks for reporting.

I have applied the correct permission to you and Angelay15. This is also fixed so will not occur in the future.

**Comment by MelodyMcKenna** [comment]
@ImSnipper The tag that Angelay15 is reporting is the tier 75 tag that comes with the free version of the BattlePass. They've just informed me that they now have access to the premium version tag and do not have the premium BattlePass, while they still don't have access to the free tag that comes with tier 75.

**Comment by ImSnipper** [comment]
I'm a little confused on which tag Tier 75 of the free battle pass should be getting...

I thought it was:
  Badge V:
    order: 27
    tag: '&8[&f&k•&r&f✪&k•&r&f&8] '
    description: '&f&oS2 Battlepass - Tier 75'
    permission: deluxetags.tag.S2BP5

@GorilloYT Can you look into this please? I know you had setup these Tiered tags for the battle pass

**Comment by GorilloYT** [comment]
Tier 75 of regular battlepass gets the one that Mel screenshot. Tier 75 of the premium gets the Battle pass star with the animated characters around it.

**Comment by ImSnipper** [comment]
Ohh I see...in that case, I don't think Tier 75 of the regular battle pass has the tag created in the DeluxeTags config.yml (unless I'm missing it) - would you mind double checking?

**Comment by ImSnipper** [comment]
I've added the BP Tier 75 Tag to the config.yml.

Mel has confirmed it's now working properly!
