### ISSUE TITLE
[BUG] Week 6 Challenge: Cookie Baker broken.

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#114]
**Describe the bug**
The Cookie Baker challenge does not count the amount of cocoa bean pods that you break correctly. I broke 16 pods (checked within logs), and the challenge recorded that I've broken 5.

**To Reproduce**
1. Read Week 6 Challenge: Cookie Baker description
2. Collect 250 (fully matured) cocoa bean pods to complete challenge.

**Expected behavior**
Breaking 1 pod equals 1 point towards the x/250 amount for the challenge.

**Screenshots**
image shows logs of me breaking pods in the last 2 hours, 4 pages with 4 logs each (16 total):
![image](https://user-images.githubusercontent.com/109165139/185247556-4d2a11a5-6f7a-4960-8113-b5e1edd1f6c4.png)

what the challenge says for me after doing the collection above:
![image](https://user-images.githubusercontent.com/109165139/185247789-a8365964-cdce-4c04-a961-cd7bcbfc2310.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
N/A

**Comment by ImSnipper** [comment]
This should be fixed now...

Can you please test and confirm?

**Comment by ImSnipper** [comment]
Confirmed fixed
