### ISSUE TITLE
[BUG] BattlePass Missing Pages

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#116]
**Describe the bug**
User *Chrisley07 reported the rewards section of the /bp does not display the second or fourth pages. It's likely skipping every other page in the display.
The player first noticed this when he kept getting the message saying they had unclaimed BattlePass rewards and couldn't find them.

**To Reproduce**
1. Unknown

**Expected behavior**
All tier levels display on the appropriate rewards page.

**Screenshots**
Zone will send the video of the issue in #s2-bug-reporting

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
The user is on the Minecraft Bedrock version and uses their laptop and tablet to play. They confirmed that the issue is present on both devices.

**Comment by ImSnipper** [comment]
Any chance the player could provide us with a video? @MelodyMcKenna

**Comment by MelodyMcKenna** [comment]
> Any chance the player could provide us with a video? @MelodyMcKenna

Yes, the video Zone sent in #2s-bug-reporting is what we received from the reporting player, *Chrisley07.

**Comment by ImSnipper** [comment]
I updated Geyser, Floodgate, and BattlePass last night.

Can you check if the player is still having this issue?

**Comment by MelodyMcKenna** [comment]
> I updated Geyser, Floodgate, and BattlePass last night.
> 
> Can you check if the player is still having this issue?

The player claims the issue is still present. Please let me know if I can assist with anything more. @ImSnipper

**Comment by foodbandit** [comment]
This player just recently updated us saying that the all the pages are showing up now so this is no longer an issue!

**Comment by ImSnipper** [comment]
Thank you for the update!
