### ISSUE TITLE
[BUG] Easy parkour reward

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#117]
**Describe the bug**
There's no cooldown for the easy parkour's 25coin reward. so you can grind coins with it.

**To Reproduce**
Do the parkour twice in a row

**Expected behavior**
1day cooldown

**Server that is affected (Hub)**

**Additional context**
Possible other parkours are the same so if your good at the medium or hard you get tons of coins.

**Comment by ImSnipper** [comment]
I set the cooldown again. Also checked medium, and hard.

Eddie confirmed easy is rewarding properly once again
