### ISSUE TITLE
[BUG] WorldEdit Perm Durations - Creative

### ISSUE THREAD

**Issue by Gallix18** [GorilloCraft/Server#118]
**Describe the bug**
When using **/upgrades** to purchase WorldEdit the first option shows a duration of 24 hours. Once purchased permissions only exist for 1 hour.

**To Reproduce**
1. Run command **/upgrades** in creative world
2. Click 'Player Upgrades'
3. Click 'World Edit I'

**Expected behavior**
Permissions will last for 24 hours. 

**Screenshots**
![image](https://user-images.githubusercontent.com/108558492/185775213-ba9314a0-07ae-4fb7-ad97-c13b2febaea0.png)
![image](https://user-images.githubusercontent.com/108558492/185775215-25dced3a-328b-49e5-a793-adc75210dc39.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Creative

**Additional context**
N/A

**Comment by ImSnipper** [comment]
Fixed!
