### ISSUE TITLE
[BUG] Week 7 battlepass

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#119]
**Describe the bug**
it says to eat 16 cooked salmon but the total is out of 32

**Screenshots**
![image](https://user-images.githubusercontent.com/42377455/185789684-0e97aaa0-e938-4f1f-b3c1-2f9f2ab126e4.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
Fixed! Thank you for reporting.
