### ISSUE TITLE
Emoji heads drop in PVP arena

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#12]
**Describe the bug**
If someone is using an emoji cosmetic and dies in the PVP arena, the emoji head will drop rather than the player's head.

**To Reproduce**
1. Activate an emoji cosmetic
2. Enter the PVP arena
3. Die

**Expected behavior**
Player heads have a chance to drop on death.

**Screenshots**
![2022-06-30_13 57 44](https://user-images.githubusercontent.com/29812480/176778144-6baa4b8a-cfd7-4a07-be76-9f4235e1f01f.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival, PVP Arena

**Additional context**
The cosmetics command will open the GUI, but cosmetics are not usable in the PVP arena. The error message "Cosmetics are not allowed in this world" appears, yet players can enter the PVP area with an emoji head active.

**Comment by ImSnipper** [comment]
This is now fixed.

Unfortunately, the only way to fix this is by removing the emote when a player enters the PvP arena, because the head drop feature thinks that the emote is the actual skull of the player, hence dropping the emote skull on death.

Thank you for reporting.
