### ISSUE TITLE
[BUG] you can do some of the premium challenges without buying the battlepass

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#120]
**Describe the bug**
some challenges you can do without buying the pass

**To Reproduce**
1. week 2 catch something challenge
2. week 6 stick handler challenge 

**Expected behavior**
only be able to complete the challenges if bought the pass

**Screenshots**
Week 6
![image](https://user-images.githubusercontent.com/42377455/185789794-d86fa581-8e9c-4ea4-b5c2-49bb758ba2e7.png)
Week 2
![image](https://user-images.githubusercontent.com/42377455/185789800-1112e2f1-3ea5-41b2-abed-2da9c23cfe61.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
Fixed! Thank you for reporting.
