### ISSUE TITLE
[BUG] Join message after reappearing from /vanish looks different

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#122]
**Describe the bug**
When reappearing after being in /vanish, the "user joined the game" og yellow-text message pops up in chat, different from our normal join message "[+] user".

**To Reproduce**
1. Enter vanish using /vanish command
2. Exit vanish using /vanish command
3. Read chat message once out of /vanish

**Expected behavior**
Rejoining after using /vanish should have the same formatted message as if you were joining that server normally.

**Screenshots**
tested with YoNoSoyGorda aka ~Yoyi:
![IMG_4188](https://user-images.githubusercontent.com/109165139/186020623-4c548354-5a2f-4556-9cf0-b173db0727c0.jpg)

**Server that is affected (Global, Hub, Survival, Creative)**
Only tested in survival, could be affected in every server

**Additional context**
Hoping this gets fixed before peeps start noticing the difference!

**Comment by MelodyMcKenna** [comment]
If there's a way, can we implement a feature that allows staff to /vanish and reappear silently without a chat message? That could be useful for some situations.

**Comment by ImSnipper** [comment]
> If there's a way, can we implement a feature that allows staff to /vanish and reappear silently without a chat message? That could be useful for some situations.

Consider it done! There will no longer be a join/leave message when a staff member activates/disables vanish mode.
