### ISSUE TITLE
[BUG] NPC nametag visibility 

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#123]
**Describe the bug**
The command /npc name -h doesn't work for disabling the visibility of the nametags, it only enables the visibility. 

**To Reproduce**
Go to a NPC and do the {/npc name -h} command to see the nametag stick and not disappear.

**Expected behavior**
The command should switch the nametag to being toggled on & off when used. 

**Server that is affected (Creative)**

**Additional context**
A few things from the plugins GitHub mentions how other scoreboard plugins could be interfering with it.

**Comment by ImSnipper** [comment]
This is resolved.
