### ISSUE TITLE
[BUG] Little orthographic error

### ISSUE THREAD

**Issue by Baterista13** [GorilloCraft/Server#124]
**Describe the bug**
On the Battlepass Rewards page, on Tier 87, you can read "REWARDS: 2x Skill XP **Bost**", where you should read "REWARDS: 2x Skill XP **Boost**".

**To Reproduce**
1. Reach Tier 87 on the Battlepass.
2. Go to the Battlepass Rewards page.
3. Go to the Tier 87 Reward.

**Expected behavior**
You should read "REWARDS: 2x Skill XP **Boost**"

**Screenshots**
![image](https://user-images.githubusercontent.com/73080986/186654961-1823cb21-5ba1-49eb-91bf-eb668c982caa.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
Fixed! Thanks for reporting.
