### ISSUE TITLE
[FEATURE] Nickname Limitations

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#125]
**Please describe the feature you think should be implemented**
Can we limit the number of characters people can use in a nickname to 15 or fewer and remove the ability to use symbols in nicknames?
I've also noticed that some players have spaces between the ~ symbol and their nickname. After looking into it, I found that those players are not using the coloured nickname command correctly, using the format `/nick #00AA00Mel` rather than the intended `/nick <color:#914839>Gorillo` as listed on the web store. When people use the incorrect format, it makes using commands like /realname [player name] impossible without knowing the exact hex code. Is there a way to limit this?

**Comment by ImSnipper** [comment]
Done! The maximum nickname limit has been set to 15 and will take effect at the daily restart. 

I will try to limit players from using the incorrect format, and force require the format be as displayed on the webstore.
