### ISSUE TITLE
[BUG] Tier 88 Spawn Egg Reward

### ISSUE THREAD

**Issue by ZonePotato** [GorilloCraft/Server#126]
**Describe the bug**
Tier 88 does not reward spawn eggs when claimed.

**To Reproduce**
1. Reach tier 88
2. Attempt to claim reward eggs

**Expected behavior**
When reaching tier 88 do /bp and claim the reward. Reward should automatically be deposited into your inventory once claimed.

**Screenshots**
The Screenshot will be attached to the bug report on discord of the member opening the reward. 

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
Member IGN CJcasket2468

**Comment by ImSnipper** [comment]
Fixed for future occurrences, and I've placed 2 Mooshroom Cow Spawn eggs in your inventory.
