### ISSUE TITLE
[BUG] Entities In Creative

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#127]
**Describe the bug**
Players can place minecarts, armour stands, and boats and can use snowballs in creative.

**To Reproduce**
1. Use /creative
2. Place/use the above mentioned items

**Expected behavior**
Players do not have permission to place Minecarts, armour stands, and boats or use snowballs.

**Server that is affected (Global, Hub, Survival, Creative)**
Creative

**Additional context**
Would Item Frames be a good idea to add to this list? I think lots of item frames could cause a lot of lag.

**Comment by ImSnipper** [comment]
Fixed!
