### ISSUE TITLE
[BUG] Week 8 bp challenge Phantom Slayer not doable 

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#128]
**Describe the bug**
it says to kill 10 phantoms but they are not enabled 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Week 8 BP

**Expected behaviour**
could swap the phantom for another mob?

**Screenshots**
![image](https://user-images.githubusercontent.com/42377455/187030911-2ba6eb37-bb31-4165-a87c-988d2599087d.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by foodbandit** [comment]
There is also a premium challenge in Week 6 called Phantom Slayer with a similar prompt, this will need to be changed as well.

**Comment by ImSnipper** [comment]
Week 6 Phantom Slayer has been changed to MAGMA_CUBE

Week 8 Phantom Slayer has been changed to ENDERMAN
