### ISSUE TITLE
[BUG] BattlePass Challenge: Ice, Ice, Baby! not working

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#129]
**Describe the bug**
BP challenge where you need to collect 150x ice is not counting

**To Reproduce**
1. Find and read week 8 BP challenges, find Ice, Ice, Baby! challenge
2. Break ice blocks to complete challenge

**Expected behavior**
Breaking (regular) naturally spawning ice blocks should be counted for the challenge.

**Screenshots**
the screenshot is from my inventory, i collected ice specifically to test the quest and it counted none of it:
![image](https://user-images.githubusercontent.com/109165139/187051751-2414349a-0459-4a98-80d3-fa7d795f063f.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
Separate BP issue: The new enderman slayer challenge for week 8 counts 0/1 instead of 0/10 as p[rompted in the description.

**Comment by ImSnipper** [comment]
Both Fixed!
