### ISSUE TITLE
[BUG] Frame rate drop in shopping district

### ISSUE THREAD

**Issue by TheSimzHelper** [GorilloCraft/Server#130]
**Describe the bug**
After teleportation, my frame rate was reduce a great deal while walking around the shopping district. In the survival area, the frame rate is fine.

**To Reproduce**
1. Teleport to shopping district.
2. Move around.

**Expected behavior**
The frame rate whitin the shopping district should be 30 and up.

**Screenshots**
https://user-images.githubusercontent.com/109096058/187057100-b1e0d091-d95e-492d-b94f-bc04d198c614.mp4

**Server that is affected (Global, Hub, Survival, Creative)**
Suvival - Shopping district.

**Additional context**
I asked Mel to walk around to test if the frame rate was different. No differences was noted from Mel.

**Comment by ImSnipper** [comment]
Interesting...I am not entirely sure what may be causing this, and it seems you are the only one experiencing this issue...

I will look into this though and see what I can find.

**Comment by apexmag** [comment]
I do as well,just been chalking it up the processing power of a console tho

**Comment by TheSimzHelper** [comment]
I just remember that before the drop frame, I was able to walk earlier in my previous game session without the drop frame rate. I happened all of a sudden when I came back later during my session.

**Comment by ImSnipper** [comment]
Thank you for the update @TheSimzHelper! Glad it seems to be working fine now....if it  happens again, feel free to message me on Discord, so that we can look more closely into it.
