### ISSUE TITLE
[BUG] Tier 97 Netherite

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#131]
**Describe the bug**
Tier 97 in the BattlePass states the reward is three netherite ingots, but when claimed gives five.

**To Reproduce**
1. Reach tier 97
2. Claim reward

**Expected behavior**
Receive three netherite ingots upon claiming

**Screenshots**
![image](https://user-images.githubusercontent.com/29812480/187060407-fc986114-2732-4753-beea-16e26974ae09.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
I'm unsure if there's a typo in the BattlePass or an error in the rewards. Is it meant to be three or five?

**Comment by ImSnipper** [comment]
Fixed, TY for reporting!
