### ISSUE TITLE
[BUG] Tier 100 Chat Tag

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#132]
**Describe the bug**
The Chat Tag from the BattlePass tier 100 reward is not available in /tags after claiming the reward.

**To Reproduce**
1. Reach Tier 100 in the BattlePass
2. Claim reward

**Expected behavior**
The tag becomes available in /tags

**Screenshots**
![image](https://user-images.githubusercontent.com/29812480/187061352-16ee7518-abea-48e5-84ba-0e5390087a41.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
Should be fixed now
