### ISSUE TITLE
[BUG] Shop Rent Duration On Outter Ring

### ISSUE THREAD

**Issue by Gallix18** [GorilloCraft/Server#133]
**Describe the bug**
Shops located along the outer ring of the shopping district do not have the same max rent duration of the inner shops (30 days.)

**To Reproduce**
1. Go to survival server
2. /shop to get to shop district
3. Rent an outer ring plot
4. Give 25 diamonds and have shop duration extend over 30 days

**Expected behavior**
Both rings of shops should have 30 day max rental periods. 

**Screenshots**
![image](https://user-images.githubusercontent.com/108558492/187094645-ef8b739e-6c2a-4942-9d19-85890cf3e6f5.png)
![image](https://user-images.githubusercontent.com/108558492/187094652-2703a1cf-618b-40da-b4df-fe01ab77f6f3.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival 

**Additional context**
Please let me know if this is intentional for the outer ring. Thanks!

**Comment by ImSnipper** [comment]
I don't believe this is intentional - I changed the max extend time to 30 days. Players won't be able to do this for the future
