### ISSUE TITLE
[BUG] Chat Game Leaderboard

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#134]
**Describe the bug**
The Chat Game leader board is not displaying the correct head for the #5 slot user. The player in #5 is SussyMoo, and the head does not match their current.

**To Reproduce**
1. See the photo below

**Expected behavior**
The leaderboards display the correct player head with their names.

**Screenshots**
![image](https://user-images.githubusercontent.com/29812480/187338892-f93c3b3e-a024-4926-97c8-6e9b0ca3cee6.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
SussyMoo has not changed their skin recently.

**Comment by ImSnipper** [comment]
This will be fixed at the daily restart.
