### ISSUE TITLE
[BUG] Enderman Slayer challenge not giving points

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#139]
**Describe the bug**
I don't fully know if this is a one time thing since I think it's worked for others but I did the Enderman Slayer challenge and in chat it showed that I completed it but I never got the 100 points. 

**To Reproduce**
1. Complete the challenge
2. See if you get the points or not 

**Expected behavior**
100% garunte to get the points on completion

**Screenshots**
![2022-09-05_10 02 03](https://user-images.githubusercontent.com/109323715/188469535-53e6ca64-b581-4d1c-a87a-1959254fa161.png)
Meant to say Bp tier level up after one of the weekly quests since 100/100 to tier up

**Server that is affected (Survival)**

**Additional context**
Only idea I got as to why it didn't work is the tenth enderman was the only one I killed outside the overworld dimension so it could be an issue with dimensions.

**Comment by ImSnipper** [comment]
This is interesting. Difficult to debug since it seems to have been a one time thing for you...I will look into the possibility of the dimensions affecting it.

I can give you some BP points when you are next on. Just let me know.
