### ISSUE TITLE
PVP Arena Respawn

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#14]
**Please describe the feature you think should be implemented**
When players use the PVP arena, it would be easier to automatically respawn or have the option to respawn back on the floating platform in the arena rather than back in the central spawn area
![2022-06-30_14 13 56](https://user-images.githubusercontent.com/29812480/176779362-deb8f194-f1b3-4db1-b8ca-c4876d2da8e3.png)
.

**Comment by ImSnipper** [comment]
I just set the essentials respawn priority to low, and set the respawn world for the PvP Arena to be the same world.

Change will take effect at restart (Will need to test first, so not going to close this yet)

**Comment by ImSnipper** [comment]
Just restarted the server, and the change is functioning as expected.

Upon death in the PvP arena, players will now respawn at the top of the platform in the PvP arena.
