### ISSUE TITLE
[BUG] People with the Edev rank lose there previous rank perks

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#140]
**Describe the bug**
Deepseermoo has lost there legend + perks since changing to Edev rank and i think itl be the same for others if they have a rank

**To Reproduce**
1. be any rank
2. change to Edev rank and you will lose the previous rank perks

**Expected behavior**
Your rank perks continue when Edev

**Server that is affected (Global, Hub, Survival, Creative)**
Global

**Comment by ImSnipper** [comment]
I fixed Deepseermoo's rank.

For future, we just need to be sure that we use the "add" command instead of "set" with luckperms
