### ISSUE TITLE
[BUG] able to kind of bypass the secret death daily challenge

### ISSUE THREAD

**Issue by cloudiskie** [GorilloCraft/Server#142]
**Describe the bug**
The daily challenge secret death also works when killing yourself and not another player

**To Reproduce**
1. get the secret death challenge as one of your daily challenges
2. kill yourself (example: i shot a arrow into the air and it hit me)
3. the challenge gets completed 

**Expected behavior**
Not 100% sure on this but i think your suppose to only have completed it when you actually kill someone else

**Screenshots**

**Server that is affected (Global, Hub, Survival, Creative)**
survival

**Additional context**
again, not sure if this is really a bug just thought i would mention it and see if there was anything you could do

**Comment by ImSnipper** [comment]
Thanks for reporting! 

Unfortunately, this isn't an easy fix since it is tracking "PLAYER" kills, and of course, you count as a player. I will report it to the plugin developer though.
