### ISSUE TITLE
[BUG] Bedrock BP Issue

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#145]
**Describe the bug**
Bedrock players are unable to scroll pass page 3 in the BP rewards pages

**To Reproduce**
1. On bedrock, go to /bp
2. Click for BP rewards in menu
3. Attempt to scroll past page 3 (past Tier 21)

**Expected behavior**
All pages should be accessible, and you should be able to scroll thru them with no issue.

**Screenshots**
Video posted in #s2-bug-reporting channel attached to this log.

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
This problem was brought up at 4am EST. One bedrock player said that they haven't had the issue, but multiple have said otherwise.

**Comment by ImSnipper** [comment]
We have updated the battle pass plugin so that rewards are automatically claimed.

This should no longer be an issue for bedrock users.
