### ISSUE TITLE
[BUG] Spawn NPC's do not work

### ISSUE THREAD

**Issue by YoNoSoyGorda** [GorilloCraft/Server#146]
**Describe the bug**
When trying to use an NPC we can't right click them. 

**To Reproduce**
1. Go to any of the NPC's at spawn
2. Try right-clicking

**Expected behavior**
Perform the action of each individual NPC

**Screenshots**
N/A

**Server that is affected**
Survival Spawn

**Additional context**
No error message appears when trying to click it.

**Comment by ImSnipper** [comment]
Fixed! Thank you for reporting.

**Comment by YoNoSoyGorda** [comment]
It broke again, none of the NPC's in survival spawn are working.

**Comment by YoNoSoyGorda** [comment]
Another NPC that is also not working is at /shop, "Shop District Information. The "Shopkeeper Egg Shop" is still working though.
