### ISSUE TITLE
[BUG] Enchantment books with multiple enchants can't be in shop

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#147]
**Describe the bug**
When trying to sell enchantment books with multiple enchants on them does not work in shops. The shop shows that its out of stock, and trying to set up the price doesn't register it in the shop buy menu.

**To Reproduce**
1. Put enchantment book in shop chest inventory
2. Set up trade in shop menu
3. Attempt to trade for book

**Expected behavior**
Should be able to trade for it.

**Screenshots**
See video tagged to this message in #s2-bug-reporting

**Server that is affected (Global, Hub, Survival, Creative)**
Survival - shop area

**Additional context**
I think this is connected to the one issue we had a while ago, where having multiple enchantments on an item would reorder them into alphabetical order. Unless selling books with multiple enchants is not a thing.

**Comment by ImSnipper** [comment]
Thank you for the update! 

I've made note of it, and will look into this. I could have swore we adjusted a setting regarding the alphabetical order...I will check into it tomorrow.
