### ISSUE TITLE
[BUG] Favourites button on the Player Warps window doesn't work.

### ISSUE THREAD

**Issue by Baterista13** [GorilloCraft/Server#149]
**Describe the bug**
When you open the Player Warps window, there is a Favourites button. However, when I click it, nothing happens, even though I set some warps as my favourites.

**To Reproduce**
1. In the game, write /pw on the chat.
2. On the Player Warps window that appears, click on the Favourites button, on the bottom left corner (Diamond icon).

**Expected behavior**
A "Favourite Warps" window appears, with only your Favourite warps.

**Screenshots**
![2022-10-06_13 02 44](https://user-images.githubusercontent.com/73080986/194307749-91db9c80-f587-4906-abc1-4ec9b7da43c7.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
Playing on Java, no mods, no lag.

**Comment by ImSnipper** [comment]
I will report this to the plugin developer - thanks for reporting this!
