### ISSUE TITLE
[FEATURE] Fish Competition Storage

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#15]
**Please describe the feature you think should be implemented**
I propose we add a command that opens a backpack-like GUI where people can store the different fish caught during the fishing competition. This feature will significantly help with the organization and accessibility of the various fish. The command could be something as simple as /fish or /fishbag.

**Comment by GorilloYT** [comment]
I don't think this is necessary. There is a 10-minute timer to prepare for the event, giving enough time to clear your inventory and find a location to fish.
