### ISSUE TITLE
[BUG] Dodgy Dealer

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#151]
**Describe the bug**
The NPC 'Dodgy Dealer' at the 100club is unresponsive. 100club quests are unavailable, and the daily coins are only available through the `/kit 100club` command.

**To Reproduce**
1. Go to X:47 Y:-38 Z:-90 in the Overworld under /spawn
2. Click on the NPC 'Dodgy Dealer'

**Expected behavior**
The 100club quests/rewards GUI appears.

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
This will be fixed at the daily restart. Apologies for taking so long to get this fixed.
