### ISSUE TITLE
[BUG] Coin Reward for Playtime

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#152]
**Describe the bug**
Discord user, Reyansh, reported that they are not obtaining the playtime coins for 1 hour of active gameplay.

**To Reproduce**
1. Active gameplay for 1+ hours

**Expected behavior**
25 coins per hour of active gameplay and a corresponding notification in chat.

**Server that is affected (Global, Hub, Survival, Creative)**
Global

**Comment by Gallix18** [comment]
This issue should be resolved now. I was able to convert the old LitePlaytimeRewards plugin information to the updated RewardsLite plugin folder.
