### ISSUE TITLE
[FEATURE] `/geyser statistics` and `/geyser advancement` permissions 

### ISSUE THREAD

**Issue by Gallix18** [GorilloCraft/Server#153]
**Please describe the feature you think should be implemented**
If possible, adding geyser.command.statistics and geyser.command.advancements permissions so that bedrock players can run `/geyser statistics` and `/geyser advancements` respectively.

**Comment by ImSnipper** [comment]
These permissions have been added to the default group.

Can a helper/mod please test when they get the chance? Thank you!

**Comment by MelodyMcKenna** [comment]
I can use both commands mentioned above successfully with my Bedrock account. Thanks so much.
