### ISSUE TITLE
[BUG] More BP Reward Issues

### ISSUE THREAD

**Issue by YoNoSoyGorda** [GorilloCraft/Server#154]
**Describe the bug**
Some players cannot see any rewards from the bp and another doesn't have autoclaim working for them

**To Reproduce**
1. Play on bedrock

**Expected behavior**
Bedrock bp is glitched in general

**Screenshots**
![image](https://user-images.githubusercontent.com/113873864/196048465-fbb6474c-38f3-455f-8689-56f81e09669d.jpeg)

**Server that is affected (Survival)**

**Additional context**

**Comment by ImSnipper** [comment]
It seems that there has been several updates to the battle pass plugin over the past couple days, which I just uploaded to the server.  I have also changed a setting in the PurPur configuration which can affect GUI's - not sure if it will have any impact, but please let those having issues with BP rewards to try again.

Thank you!

**Comment by ImSnipper** [comment]
One more thing: I just tried on my bedrock account, and I was able to successfully navigate between all the pages.

Hopefully it's fixed...

If not, please reopen this issue
