### ISSUE TITLE
[BUG] Permanent fishing contest

### ISSUE THREAD

**Issue by Baterista13** [GorilloCraft/Server#156]
**Describe the bug**
The fishing contest is bugges. It's going on forever. It has been going for, at least, 3 or 4 hours.

**To Reproduce**
1. Join the server;
2. Fish;
3. You can see that you can fish the special items from the contest, and that lasts for well over 10 minutes.

**Expected behavior**
Fishing contests should last 10 minutes each time.

**Server that is affected (Global, Hub, Survival, Creative)**
Survival.

**Comment by ImSnipper** [comment]
The daily restart seems to have fixed this.
