### ISSUE TITLE
Pigman Morph Terrifying Noise

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#16]
**Describe the bug**
Left-clicking while using the Pigman morph cosmetic does not create a terrifying noise.

**To Reproduce**
1. Activate the Pigman morph cosmetic
2. Left-click

**Expected behavior**
A terrifying noise

**Screenshots**
![2022-06-30_17 19 50](https://user-images.githubusercontent.com/29812480/176799232-f3931e8b-f5d2-4590-8c13-e801475e7342.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Global

**Additional context**
All volume settings were on while testing this. Other players are also unable to hear the terrifying noise.

**Comment by ItsMeGriff** [comment]
Seems to be a bug in the plugin, closing for now

**Comment by ImSnipper** [comment]
Yep, that is right @ItsMeGriff. It will be fixed in the next update.
