### ISSUE TITLE
[BUG] Daily challenge reset notification duplicate 

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#17]
**Describe the bug**
The 'Daily challenges have been reset' notification is announced twice. It's not a very big deal but thought I'd make a note of it.

**To Reproduce**
1. Be online when the daily challenges are reset

**Expected behavior**
Only one announcement.

**Screenshots**
![image](https://user-images.githubusercontent.com/90524760/176872152-14b92ff7-05a4-488e-8c51-7d3089cc81dc.png)
**Server that is affected (Global, Hub, Survival, Creative)**

**Comment by ImSnipper** [comment]
This should be fixed now...will have to see what happens at next daily reset. If the issue still occurs, please open this issue back up

**Comment by GorilloYT** [comment]
The reset notification is now showing 4 times in chat. 

![image](https://user-images.githubusercontent.com/90524760/177034710-1fdbbd9f-011f-441e-8017-fc71f7196415.png)

**Comment by ImSnipper** [comment]
I took a look through all of the configuration files for the battle pass.

There are currently 5 daily challenges, and the configuration was "daily-quest-amount: 7". I believe this may have caused some sort of conflict and caused the notification to appear several times....If this still doesn't fix the issue, I will reach out to the developer of the plugin.
