### ISSUE TITLE
Duplicate Treasure Rewards

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#19]
**Describe the bug**
Receiving a duplicate treasure does not reward coins.

**To Reproduce**
1. Go to the /hub
2. Buy a treasure chest
3. Opening chests can sometimes award treasures already owned by the player

**Expected behavior**
Duplicate treasures award a certain amount of coins based on rarity.

**Screenshots**

**Server that is affected (Global, Hub, Survival, Creative)**
Hub

**Additional context**

**Comment by ImSnipper** [comment]
Thank you for reporting! This should be fixed now.

If a player already has the cosmetic, they will get instead get ammo for gadgets, followed by coins. 

Let me know if any more issues
