### ISSUE TITLE
[BUG] able to move npc with wither

### ISSUE THREAD

**Issue by cloudiskie** [GorilloCraft/Server#20]
**Describe the bug**
When morphed into the wither, the blasts are able to move NPCs from where they were standing

**To Reproduce**
1. Morph into wither cosmetic
2. left click at a npc
3. the npc gets shot backwards

**Expected behavior**
It it probably not at all supposed to be able to move and tamper with things in the hub

**Screenshots**
![2022-07-01_17 23 33](https://user-images.githubusercontent.com/108499451/176979799-3f0f5b80-6efe-4ac0-a3ed-76008748bf0f.png)      (im not familiar with GitHub, if that screenshot didnt work i can send it in the discord)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival: Completely turned off, i cant shoot anything
Creative: Can only shoot while inside my own claim
Hub: Can shoot anywhere at anything

**Additional context**

**Comment by ImSnipper** [comment]
Thank you so much for the detailed information about each server being affected! 

I placed some barriers behind the NPC's in the hub. If it becomes an issue, we can disable the effect in the hub too (just like it is on Survival).

Thanks!
