### ISSUE TITLE
[BUG] Grave Zombie

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#21]
**Describe the bug**
When attempting to access someone's grave, no grave zombie spawns.

**To Reproduce**
1. Open a player's grave chest

**Expected behavior**
A strong zombie is supposed to spawn to "Protect" the grave.

**Screenshots**
![2022-07-01_17 54 47](https://user-images.githubusercontent.com/29812480/176980713-b490184e-775d-486c-ae04-46df2617c008.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
There is a short video posted on Discord of me accessing CloudSkie's grave.
https://discord.com/channels/872206646955376680/990270578709643315/992594787683274752

**Comment by ImSnipper** [comment]
I've updated the information at the tutorial area to reflect the changes with Zombie spawning.

Thank you!

@GorilloYT when next on, can you please verify how long a grave should last for? It's currently set to 3 hours - not sure if this is intentional.
