### ISSUE TITLE
[BUG] Custom nickname not changing in Creative mode.

### ISSUE THREAD

**Issue by Baterista13** [GorilloCraft/Server#22]
When I execute the command "/nick <nickname>", my nickname on the chat changes, but doesn't change on the TAB player list.

**Screenshot**
![2022-07-02_12 55 24](https://user-images.githubusercontent.com/73080986/177000063-03acf110-a5c7-4531-9a7a-577cddfa3e16.png)
![2022-07-02_13 00 30](https://user-images.githubusercontent.com/73080986/177000066-d0488979-40c3-44e7-bf0f-346c4aa95810.png)

**Server that is affected (Global, Hub, Survival, Creative)**
I've seen this happening only in the Creative server.

**Comment by ImSnipper** [comment]
This is fixed now in the hub, and creative. Seems to have been an issue with one of the placeholders. Thanks for reporting!
