### ISSUE TITLE
[BUG] I can't use WorldEdit in the Creative server

### ISSUE THREAD

**Issue by Baterista13** [GorilloCraft/Server#23]
**Describe the bug**
I can't use WorldEdit in the Creative server, even though I'm a donator. Donators are supposed to have permanent access to WorldEdit, as stated in one of the attached screenshots. When I try to receive the world edit wand from the Information NPC, on the Creative server spawn, an error happens, as you can see in one of the screenshots. Also, when I try to use the Wooden Axe in my plot, nothing happens, as expected.

**Screenshots**
![2022-07-02_13 02 43](https://user-images.githubusercontent.com/73080986/177000309-41e02622-d123-46b2-97e7-406b2ccb87ca.png)
![2022-07-02_13 02 51](https://user-images.githubusercontent.com/73080986/177000316-47be8c83-0ede-431d-86ef-0ac7f458b003.png)

**Server that is affected**
Creative

**Comment by ImSnipper** [comment]
Thanks for the report! We decided on Legend, and Legend+ to have permanent access to world edit. I will update that menu to be more specific indicating it is for Legend and above.

Thank you!
