### ISSUE TITLE
[BUG] Gadget have no ammo when you have ammo

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#24]
**Describe the bug**
in survival. you have no ammo when you have ammo in the hub

**To Reproduce**
1. equip a gadget
2. Have ammo in the hub

**Expected behavior**
universal ammo?

**Screenshots**
Survival:
![image](https://user-images.githubusercontent.com/42377455/176999499-0999d67c-33db-4127-aa89-c35d4dc5fe14.png)
Hub:
![image](https://user-images.githubusercontent.com/42377455/176999518-e98f3492-d77e-4d51-8f6e-c47edd3c257a.png)

Affects:
Hub, Survival

**Comment by ImSnipper** [comment]
Thanks for reporting! We actually haven't setup the database for ammo to be global yet, but will prior to the server opening.

Will let you know when it is global, so that we can test it. thanks!
