### ISSUE TITLE
[BUG] Battlepass Tier 73 rewards a tag we've removed

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#25]
**Describe the bug**
We removed the 'Sweat' tag, but it's still an unlockable reward for tier 73 in the battlepass.

**To Reproduce**
1. Open the battle pass menu
2. Head to tier 73

**Expected behavior**
The reward should be replaced for a tag that is still in the game.

**Screenshots**
![2022-07-02_21 50 21](https://user-images.githubusercontent.com/90524760/177015875-b157842d-3a40-4557-98b0-d80af5f9a1fa.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
Going to close this issue, since Gorillo made some changes earlier, replacing the Tier 73 reward, and updating the BattlePass tag rewards.
