### ISSUE TITLE
[BUG] Buying tags and not receiving them

### ISSUE THREAD

**Issue by Baterista13** [GorilloCraft/Server#26]
**Describe the bug**
 I think I reported this some time ago, but is happening again. I bought the VeryHappy Tag, and instead got the Peace tag, which I already had. I also received the Peace tag some time ago, when I tried to buy the Music tag.

**Expected behavior**
I expected to receive the VeryHappy tag, instead of the Peace tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/73080986/177017681-e0189537-8386-4911-87d4-1645b6f0d52c.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
This is now fixed! 

It seems that when removed some tags the other day, I forgot to update the order and caused some permissions to be applied incorrectly. Was an issue on creative too - both are fixed now! thanks for reporting
