### ISSUE TITLE
[FEATURE] /rules cmd run added to Server Information Tab

### ISSUE THREAD

**Issue by Gallix18** [GorilloCraft/Server#27]
If possible, could we please add "Click to view the /rules" to the end of the Server information tab in the /help menu. The expected outcome would then be for /rules to be run upon clicking the tab in the same way that clicking on the Vote tab pulls the voting websites into the chat for the player.  

![image](https://user-images.githubusercontent.com/108558492/177018058-561e66dc-3a7a-4fa8-89b8-f9a7132b3911.png)

**Comment by ImSnipper** [comment]
Done! Added to Survival and Creative. I also copy and pasted the same rules file from Survival onto the hub and creative.

Thanks!
