### ISSUE TITLE
[BUG] Chat does not work in Creative

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#28]
**Describe the bug**
When you type something in creative mode it doesn't send the message.

**To Reproduce**
1. Enter the creative server.
2. Type something into chat

**Expected behavior**
The message should send as usual.

**Server that is affected (Global, Hub, Survival, Creative)**
Creative

**Comment by ImSnipper** [comment]
This is fixed now.

Seems to have been an issue with the chat filter plugin, and when we updated the database last night.

Thanks for reporting!
