### ISSUE TITLE
[BUG] Bugged info text when sitting down

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#29]
**Describe the bug**
When sitting down, the text says "Use your <translatekey:key.sneak> to get back up". However, it works fine on the Creative server. 

**To Reproduce**
1. Go to the survival server
2. Right-click to sit on a block (stair, slab, lilypad etc)

**Expected behavior**
The message to be 'Use your sneak key to get back up'.

**Screenshots**
![2022-07-03_18 36 58](https://user-images.githubusercontent.com/90524760/177051187-ebe084c1-3848-4569-a4db-8e572f14e079.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
Fixed!
