### ISSUE TITLE
mod commands

### ISSUE THREAD

**Issue by apexmag** [GorilloCraft/Server#33]
using /ignoreclaims is a big thing for the mods to be able to use. works in survival but not creative world which could be needed if theres an issue that needs to be removed or altered. if needed i can give examples of why.

it would also be nice if we had the ability to use /otp or /tpa from the different worlds, i.e., if i have someone in creative world and im in survival i have to tp to the hub first then to creative then /tpa, /tphere or /otp to their last spot.

**Comment by ItsMeGriff** [comment]
1. As a moderator you will automatically have access to clear and destroy other players plots. It just won’t be the ignore claims command as it is a completely different plugin. I will double check the staff guide and see if it’s listed in there and if not I will add a section. 

2. This is not possible as the creative and survival servers are 2 completely different Minecraft instances not just 2 different worlds. But to access another server you don’t have to always go back to the hub you can simply just do /server <creative or survival> then you have to execute the /tp command.
