### ISSUE TITLE
[FEATURE] Discord-Global Chat Bridge

### ISSUE THREAD

**Issue by Gallix18** [GorilloCraft/Server#35]
A feature that allows cross chat compatibility between a specified discord channel and in-game global chat. This would be only for the purposes of moderation at this time. Previously we used the DiscordSRV plugin (https://dev.bukkit.org/projects/discordsrv) to accommodate this. 

Features of this plugin that were most valuable:
- User login data (including when users joined, joined for the first time, and left the server)
- User death notifications
- Usernames/Nicknames of users who sent the messages  
![image](https://user-images.githubusercontent.com/108558492/178041387-68383d6f-2ccc-4914-a12d-bc6ae29ae139.png)

With discord being able to log all of the messages sent in a channel with no time/date restrictions and the ability to utilize discords search function to find specific messages sent through the #in-game channel, it became one of our most valuable tools for moderation and ticket investigations.

**Comment by ImSnipper** [comment]
This has been implemented! Feel free to suggest any additions, changes, etc.
