### ISSUE TITLE
[BUG] A bedrock player cannot see villager enchanted book trade

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#38]
**Describe the bug**
A bedrock player "*JhonOfinley" cannot see a villager enchanted book trade. (not sure if this is just for certain devices or all bedrock players).

**To Reproduce**
1. Be on bedrock
2. Trade with a librarian villager
3. Hover over a enchanted book trade

**Expected behavior**
To show what the enchanted book is.

**Screenshots**
![image](https://user-images.githubusercontent.com/90524760/178139589-713dc6bf-a062-4a9a-8381-66aba5431394.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ItsMeGriff** [comment]
This seems to be a Xbox-only issue as other bedrock clients can see enchanted books

**Comment by ImSnipper** [comment]
I am reporting this issue to GeyserMC to see if this is something that can be fixed.

**Comment by GorilloYT** [comment]
Update: the book was Sweeping edge which isn't available on Bedrock - so we believe this could be the reason.
