### ISSUE TITLE
[BUG] Snow/iron golem glitch

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#39]
**Describe the bug**
Creating a snow or iron golem will replace your helmet slot with a carved pumpkin, as well as creating the snow golem. This causes you to lose your helmet. (I tested on single player to make sure it was a server issue and it works fine on there). 

**To Reproduce**
1. Wear a helmet
2. Create a snow/iron golem

**Expected behavior**

Creating a golem should not also place the carved pumpkin in the head slot. It should just create the pumpkin without affecting the player's armour. 

**Screenshots**

I have posted a video in the s2-bugs reporting channel (too big for here)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ItsMeGriff** [comment]
Found the plugin at fault. Working on fix.

**Comment by ItsMeGriff** [comment]
issue fixed
