### ISSUE TITLE
[FEATURE] Disable TP commands in the PVP arena

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#41]
**Please describe the feature you think should be implemented**
Disable tp commands in the PVP arena, especially /tpahere. This will prevent players from being tricked and getting TP'd into the arena unknowingly.

**Comment by ImSnipper** [comment]
The following commands have been blocked in the PvP arena: /tpa, /tpahere, /tpaccept, /tpdeny, /sethome.

If any others come up, please let me know!
