### ISSUE TITLE
[FEATURE] Make the PVP and Shop district void worlds

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#43]
**Please describe the feature you think should be implemented**
The PVP and Shop worlds take a lot of time to render in. Maybe changing the surrounding area to void would make the world load in quicker?

**Comment by ItsMeGriff** [comment]
Investigating the chunk loading issue

**Comment by ImSnipper** [comment]
We have increased max-concurrent-sends: in paper-global.yml. Based on some research in the Paper/PurPur Discord, this seems to have fixed chunk loading for servers with the same issue. Will close if this turns out to fix

**Comment by ItsMeGriff** [comment]
Fixed
