### ISSUE TITLE
[FEATURE] Add a purchase confirmation to shop plots

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#44]
**Please describe the feature you think should be implemented**
To prevent accidentally right-clicking a shop plot, implement a "Are you sure you'd like to purchase this plot".

**Comment by ItsMeGriff** [comment]
Looking for a way to implement this

**Comment by ImSnipper** [comment]
Unfortunately, we are not able to make progress on this feature. We need the developer of Advanced Region Market to implement this feature and it seems he is pretty inactive on Spigot/Discord...

In the meantime, I am going to add a line to the hologram in the shopping district warning players that right clicking a shop sign will take their diamonds.

Closing for now, but will reopen once I hear back from the developer.
