### ISSUE TITLE
[BUG] Name tags don't work

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#45]
**Describe the bug**
Right-clicking a pet with a name tag removes the name tag from your inventory, but does not add the name to the pet. (This was tested on a dog).

**To Reproduce**
1. Right-click a name tag on an animal.

**Expected behavior**
The name should get added to the pet.

**Screenshots**

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
This seems to be working for Giz and I. Tested it out a couple different mobs (colors too), and the name was applied to the mob. 

Has anyone else run into this issue?

**Comment by apexmag** [comment]
i can try to replicate when i get back online

**Comment by foodbandit** [comment]
i just tried to name my pet today (7/15), and the name is still not showing up for me.

**Comment by ImSnipper** [comment]
We've narrowed down that this is only affecting tamed animals. You can successfully name an animal that is NOT tamed.

Looking into a solution.

**Comment by ImSnipper** [comment]
At last, this is fixed! 

Oddly enough, seems to have been an issue with the TAB plugin! Very weird...but tested, and works!
