### ISSUE TITLE
[FEATURE] Looper Command

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#48]
**Please describe the feature you think should be implemented**
The command /looper would first set the user into /vanish, then Spectator mode, and then automatically loop to each online player for 3-5 seconds. The key feature of this command is a quick check-in for all online players without manually teleporting to each one.

I'm unable to find which plugin uses this command, and there's a possibility that it's custom-made.

In the past, this command has helped find server issues, find lag machines, and enforce server /rules.

**Comment by ImSnipper** [comment]
Was this a feature on GorilloCraft S1?

**Comment by MelodyMcKenna** [comment]
> Was this a feature on GorilloCraft S1?

No, this was not in GorilloCraft. It's a command I used elsewhere and an idea I proposed at the start of S1, but I could not find the correct plugin.

**Comment by ImSnipper** [comment]
Yeah, I was doing a bit of research and I couldn't find anything either...must be a completely custom plugin.

Unfortunately, this isn't something we can implement right now but I will make note of it to @ItsMeGriff and perhaps he can whip something up in his free time.
