### ISSUE TITLE
[FEATURE] PVP Arena No Keep Inventory

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#49]
**Please describe the feature you think should be implented**
To prevent any scams and make sure everyone knows the dangers of the PVP Arena, can we add something above the entry stating that keep inventory is off and there are no /graves in the arena? Making it super clear there's a chance to lose your items by going in can help prevent issues in the future
![2022-07-11_21 34 10](https://user-images.githubusercontent.com/29812480/178409592-06a800f2-3ec7-4220-8adb-9e5c35d4b155.png)
.

**Comment by ItsMeGriff** [comment]
Added by Giz
