### ISSUE TITLE
moderator deathchest command list

### ISSUE THREAD

**Issue by apexmag** [GorilloCraft/Server#51]
we had a deathchest command list last season that proved very useful at times for players deaths. whether a siuation of they cant scroll high enough to see the coordinates anymore before time ran out or the chest was in another claim or in the sky etc 
![Screenshot_2022-04-09_5 51 12_AM](https://user-images.githubusercontent.com/99737508/178495824-7d3ffe68-ff43-498e-9a8a-6c7e265c8f16.png)

**Comment by ImGiz** [comment]
You should have permissions now to see other players deathchests/locations. The command used for this is /dc list player.
