### ISSUE TITLE
Battle Pass Tier 7 Mythical Chest

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#52]
**Bug description:**
Players are not receiving the Mythical Chest prize for unlocking tier 7 in the Battle Pass. Had 2 players open up tickets in discord to report this so far.

**Steps to reproduce the behavior:**
1. Earn 700 BP points to unlock Tier 7 in the Battle Pass,
2. Click on Minecart icon in BP menu to claim Mythical Chest reward.

**Expected behavior**
Receive a Mythical Chest and be able to unlock chest in hub.

**Screenshots**
![image](https://user-images.githubusercontent.com/109165139/178540552-e1b3885b-4533-4af8-a449-1c677d0bf713.png)
*image from user in server showing that they completed tier 7.

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
As mentioned before, 2 players have come to staff about this issue so far.

**Comment by ImGiz** [comment]
For Griff

**Comment by ItsMeGriff** [comment]
> > Just confirming that they are going to the Hub and redeeming this reward there. They need to claim this reward on the Hub server and not on survival.
> 
> Does this mean they need to go to the /hub before claiming any /bp minecart rewards containing treasures? I went to the /hub and found that /bp doesn't appear to work there. ![image](https://user-images.githubusercontent.com/29812480/178595728-45ab05fb-768c-4318-bb76-b55fe67d8600.png)

No they need to go to the hub to redeem the mythical crate which is directly behind were you spawn in the hub. The reason for this is because some cosmetics are disabled on survival but not the hub or creative so it allows them to get even more cosmetics. The downside is that they do have to go to the hub to redeem.

**Comment by MelodyMcKenna** [comment]
> > > Just confirming that they are going to the Hub and redeeming this reward there. They need to claim this reward on the Hub server and not on survival.
> > 
> > 
> > Does this mean they need to go to the /hub before claiming any /bp minecart rewards containing treasures? I went to the /hub and found that /bp doesn't appear to work there. ![image](https://user-images.githubusercontent.com/29812480/178595728-45ab05fb-768c-4318-bb76-b55fe67d8600.png)
> 
> No they need to go to the hub to redeem the mythical crate which is directly behind were you spawn in the hub. The reason for this is because some cosmetics are disabled on survival but not the hub or creative so it allows them to get even more cosmetics. The downside is that they do have to go to the hub to redeem.

I see. Thanks for the confirmation. I teleported to one of the users as they created the support ticket on Discord and saw they were at the treasure crates. It appeared they were trying to do it correctly.
