### ISSUE TITLE
[BUG] Battlepass Point Requirement

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#53]
**Describe the bug**
The Battlepass description states that 100 points are required for each tier; however, I'm currently showing tier 11 with 125/150 points. I'm unsure if this is only a display issue or if the tiers are affected by different point requirements.

**To Reproduce**
1. Reach Battlepass Tier 11 by completing /bp quests.
2. Use /bp to check the point status.

**Expected behavior**
Increase Battlepass tier every 100 points.

**Screenshots**
![2022-07-12_15 53 25](https://user-images.githubusercontent.com/29812480/178612689-ab9e3ee4-782c-436e-b0cd-6b331a9c1ba9.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by ImSnipper** [comment]
This is now fixed! Thanks for reporting.
