### ISSUE TITLE
unobtainable tutorial link

### ISSUE THREAD

**Issue by apexmag** [GorilloCraft/Server#54]
Issue found by a
![2022-07-13_11 43 43](https://user-images.githubusercontent.com/99737508/178718370-d23750c9-9468-4302-98f1-e288cc4b5724.png)
 player of clicking the tutorial link sign in the spawn info walk through area on the shopkeepers board. States players don't have permission to receive the link

**Comment by ImSnipper** [comment]
This should be fixed.

Can you please confirm? Thanks!
