### ISSUE TITLE
[BUG] able to dup some heads

### ISSUE THREAD

**Issue by cloudiskie** [GorilloCraft/Server#56]
**Describe the bug**
SussyMoo broke a warden head that was on the wall in my claim, and even tho it it stayed on the wall it also got placed in his inventory. He also tried it with other and a it worked with some others as well

**To Reproduce**Steps to reproduce the behavior:
1. Player breaks a specific head in a claimed area they are not trusted in
2. the head gets put in their inventory but also stays on the wall
3. they can continue to do this again and again with the same head
**Expected behavior**
Its suppose to stay on the wall after a player tried to break it and not go into their inventory

**Screenshots**

**Server that is affected (Global, Hub, Survival, Creative)**
only tested it in sur

**Additional context**
i broke and replaced the block and it still continued to happen

**Comment by ImGiz** [comment]
Was able to replicate the issues. Was temporarily resolved through disabling the HeadDrop plugin. Will have to look into fixing it or finding something different to use for mob head drops. Thanks for the report.
