### ISSUE TITLE
[FEATURE] Things to disable in creative

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#57]
**Please describe the feature you think should be implemented**
A few things to disable in creative to prevent lag machines from being created. 

- Minecarts
- Boats
- Wither spawning
- Armour stands

**Comment by ImSnipper** [comment]
The following items have been prevented from being placed:

      - 'minecraft:armor_stand'
      - 'minecraft:oak_boat'
      - 'minecraft:spruce_boat'
      - 'minecraft:jungle_boat'
      - 'minecraft:acacia_boat'
      - 'minecraft:dark_oak_boat'
      - 'minecraft:mangrove_boat'
      - 'minecraft:minecart'
      - 'minecraft:chest_minecart'
      - 'minecraft:furnace_minecart'
      - 'minecraft:tnt_minecart'
      - 'minecraft:hopper_minecart'
      - 'minecraft:oak_chest_boat'
      - 'minecraft:spruce_chest_boat'
      - 'minecraft:birch_chest_boat'
      - 'minecraft:jungle_chest_boat'
      - 'minecraft:acacia_chest_boat'
      - 'minecraft:dark_oak_chest_boat'
      - 'minecraft:mangrove_chest_boat'
