### ISSUE TITLE
shortened/nickname commands

### ISSUE THREAD

**Issue by apexmag** [GorilloCraft/Server#58]
things such as /whisper used to be /w and /vanish was /ev.

the other aspect of send a private message is that it has  to be spelt exact which is difficult when most or a lot have nicknames and those do not get picked up by that command. 

current Example: /whisper xXZoneXx8520
requested feature example: /w zone <message> 

this helped alot of our console bedrock and PE players bc its muc more difficult to type on the controller or in the small chat window of PE while bouncing between letter and number screens.

**Comment by GorilloYT** [comment]
A few commands we already have that you might find useful:

/v can be used to vanish.
/r <message> can be used to message the last person who messaged you.

**Comment by ItsMeGriff** [comment]
I thought I added the ability to be able to tab names when doing /msg. Could you report back if that’s not the case.

**Comment by ImSnipper** [comment]
Can confirm that /v is functional. 

I would recommend using /msg to message people on the server, and /r to reply, as Gorillo mentioned.

If you have any other ideas for shortened commands, let us know!
