### ISSUE TITLE
[BUG] Graves Tutorial Time Limit

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#59]
**Describe the bug**
The Player Graves tutorial sign in /spawn does not display the correct time limit for /graves.

**To Reproduce**
1. Use /warp tutorial
2. Check the Player Graves tutorial board at coords: 19 100 -102

**Expected behavior**
Tutorial reads 15-minute timer on /graves.

**Screenshots**
![2022-07-15_06 36 34](https://user-images.githubusercontent.com/29812480/179235509-c67117c1-ff49-4bc9-833f-e496e0ba7a4a.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by ImGiz** [comment]
Thanks for the report. I have fixed the sign in question!
