### ISSUE TITLE
[BUG] You cannot dismount on horse mount cosmetics

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#6]
**Describe the bug**
When dismounting on a horse cosmetic. it says, "Don't disembark here!" and you get stuck on it. the only way to get off the mount is to despawn it in the menu or disconnect from the server

**To Reproduce**
1. Have a horse/mule/donkey cosmetic mount
2. Dismount

**Expected behavior**
Dismount the horse

**Screenshots**
![2022-06-30_16 51 03](https://user-images.githubusercontent.com/42377455/176723010-506c66bb-0038-4789-9b84-68a103430db3.png)

Affects Globally

**Comment by ImSnipper** [comment]
This is now fixed...seemed to have been an issue with world guard.

You can now dismounting from a cosmetic.

Thank you for reporting.
