### ISSUE TITLE
LEGENDARY CHEST DROP RARE CRATE - NOT WORKING

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#60]
**Describe the bug**
User *JhonOfinley used a rare crate key (obtained from vote crate key roll) and rolled a Legendary Chest. When going to open the chest in hub, chest said that they did not own any Legendary Chests.

**To Reproduce**
1. Obtain rare crate key and use on Rare Crate chest.
2. Roll/win the Legendary Chest prize.
3. Go to hub and open chest thru any of the three Treasure Chest chests inside hub.

**Expected behavior**
After rolling Legendary Chest from Rare Crate, you should own and be able to open Legendary Chest in spawn Treasure Chest chests.

**Screenshots**
(screenshots from *JhonOfinley)
![image](https://user-images.githubusercontent.com/109165139/179343821-8fa892e6-cb81-4bfc-9da5-e21443d8d614.png)
![image](https://user-images.githubusercontent.com/109165139/179343827-005cf5f4-a280-42dd-9a20-3a3b430519e0.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival/Hub

**Additional context**
Player will need a replacement Legendary Chest whenever possible.

**Comment by ImSnipper** [comment]
Thank you for reporting.

The command that is currently running to give the cosmetic treasure chest is conflicting with the party chat system. 

When *JhonOfinley is next online, we can give him the Legendary treasure chest. I will update the command being executed in the rare care tomorrow.

**Comment by ImSnipper** [comment]
The bug has been fixed so that it does not happen for future players.

I've told Skee to let me know when *JhonOfinley is next online so that we can manually give the treasure chest.
