### ISSUE TITLE
BATTLE PASS TIER 17 - NO REWARD BUG

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#61]
**Describe the bug**
Player CJcasket2468 did not receive their 2x Normal Treasure chests from Tier 17 in the battle pass.

**To Reproduce**
1. Complete Tier 17 in the battle pass.
2. Receive reward of 2x Normal Treasure chests.
3. Go to hub to open chests.

**Expected behavior**
Receive and be able to own/open 2x Normal Treasure chests after Tier 17 completion.

**Screenshots**
from CJcasket2468:
![image](https://user-images.githubusercontent.com/109165139/179382150-426377b8-840f-477e-b3ad-c8b54ac443f1.png)
![image](https://user-images.githubusercontent.com/109165139/179382154-651eebc0-daf8-477c-8fa1-5fbb6e9988e9.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival/Hub

**Additional context**
Player will need replacement reward whenever possible.

**Comment by ImSnipper** [comment]
Thank you! This has been fixed. Again, seems to have been an issue with the cosmetics plugin conflicting with the party chat plugin. I've updated all the commands now, so hopefully this will no longer be an issue.

I have manually given the player 2 normal treasure chests.
