### ISSUE TITLE
Treeciraptor doesn't work properly

### ISSUE THREAD

**Issue by TheSimzHelper** [GorilloCraft/Server#62]
**Describe the bug**
On Java, the Treeciraptor, mana ability from Foraging doesn't work properly in Survival.

**To Reproduce**
Where we supose to right click a tree with an axe and left click it. But all it does it's stripping the log then once this block is mined a message telling that the ability is activated but nothing out of the ordinary happens.

**Expected behavior**
A tree should be complety dismantled and looted withtin the inventory. Did what had to do on the ability's description page.

**Screenshots**

https://user-images.githubusercontent.com/109096058/179385927-63ccb5cd-fd3d-4c88-a464-8f3a114db22f.mp4

**Additional context**
3 seconds is not enough. The time base would have to be doubled to have an interesting use. Otherwise 3 seconds is just not enough. I propose to do so for the time of the effect : 6s to 10s on next level up.

**Comment by ImGiz** [comment]
Thank you for bringing attention to this. With this skill, you have to hold SHIFT while right clicking, we believe that is where the confusion is. Since the tip doesn't indicate that, we are currently changing it though! Thanks for the report.

**Comment by TheSimzHelper** [comment]
Thank you!
