### ISSUE TITLE
[BUG] Battlepass Tier 25 Rewards

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#66]
**Describe the bug**
The Battlepass Shield and Battlepass Helmet are not awarded after claiming them at tier 25.

**To Reproduce**
1. Reach tier 25 in /bp
2. Claim both rewards

**Expected behavior**
Obtain both the Shield and Helmet after reaching tier 25 and claiming.

**Screenshots**
![2022-07-18_21 58 36](https://user-images.githubusercontent.com/29812480/179668603-2067eb27-bc6b-4f59-8778-946ba8d28483.png)
![2022-07-18_21 58 38](https://user-images.githubusercontent.com/29812480/179668616-49c868fa-95b6-4586-9c03-242b4ce667fe.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by foodbandit** [comment]
along with this, Tier 10 reward of BattlePass Axe is also not working. i sent a video of me trying to receive it in #s2-bug-reporting.

**Comment by ItsMeGriff** [comment]
Fixed. Just a typo in the config
