### ISSUE TITLE
[BUG] Upgrades Command Unusable In /Hub

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#67]
**Describe the bug**
The Useful Commands info board states that /upgrades is an available command to use globally; however, it's an unknown command when used in the /hub, where the info board is.

**To Reproduce**
1. Go to -44 56 14 in the /hub. This is where the info board is.
2. Use the /upgrades command
3. Error message "Unknown Command. Type "/help" for help."

**Expected behavior**
The /upgrades command brings up the /upgrades menu.

**Screenshots**
![2022-07-18_23 56 15](https://user-images.githubusercontent.com/29812480/179686584-acb0a44e-9fa2-4ab4-8006-4b135e6a6cfa.png)
![2022-07-19_00 01 20](https://user-images.githubusercontent.com/29812480/179687042-09e6d126-ef7b-48f3-aa9d-9922f6f456f5.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Hub

**Additional context**
I'm unsure if the /upgrades command is supposed to be available in the /hub or if the /hub is considered a server.

**Comment by ImSnipper** [comment]
This is now fixed, thank you! 

The upgrade shop in the hub was defaulting to /shop, but now, both will work.
