### ISSUE TITLE
[BUG] Shopkeeper Sign Not Resetting With Plot

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#68]
**Describe the bug**
There's a Shopkeeper sign floating in the air in Just_The_Void's new plot, Shop26. The Shopkeeper belongs to *SourLemonsMC.

**To Reproduce**
1. Use /shop
2. Go to Shop26 at -26 -60 -39

**Expected behavior**
A shop plot archives and resets completely when out of time.

**Screensh
![2022-07-19_11 12 22](https://user-images.githubusercontent.com/29812480/179821939-0f221607-6f56-4e70-9061-a0b8fa7b8ae2.png)
ots**
![2022-07-19_11 12 26](https://user-images.githubusercontent.com/29812480/179821958-0ee0065f-afa0-460c-beb6-c6a9fc8769c8.png)
![2022-07-19_11 12 28](https://user-images.githubusercontent.com/29812480/179821968-2ec4a27d-0389-4b27-ae5c-63bae538798e.png)
![2022-07-19_11 28 13](https://user-images.githubusercontent.com/29812480/179822933-abea127d-5d2e-4450-b2cb-5a450fc92df3.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
I cannot find the container that the Shopkeeper is connected to in the area. There are trades set up, but it appears to be out of stock. I'm also unable to check if *SourLemonsMC is a member of Shop26 with build perms.
I cannot /ignoreclaims and remove the Shopkeeper egg. The last screenshot above was taken after I attempted to break the sign.

**Comment by ImSnipper** [comment]
Thank you for reporting! 

Unfortunately, this seems to be a compatibility issue between AdvancedRegionMarket (plugin we use for the plots), and the Shopkeepers. AdvancedRegionMarket is unable to hook into Shopkeepers so I will report this issue to the developer of the plugin.

In the meantime, moderators can delete shops, if this occurs again. 
Shift + Right Click on the sign to delete.
