### ISSUE TITLE
[BUG] Cannot rename pets

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#7]
**Describe the bug**
When trying to rename a pet, you receive a message: "This feature is coming soon!"

**To Reproduce**
1. Open the cosmetics menu
2. Enable any pet
3. Click the nametag to rename
4. You'll receive the message in chat. 

**Expected behavior**
The ability to give the pet a name. 

**Screenshots**
Section from the config:
![image](https://user-images.githubusercontent.com/90524760/176729339-9e5f95e0-718c-4221-a475-ae454be5eb93.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Global

**Comment by ItsMeGriff** [comment]
Currently don’t think this is a feature in the plug-in looking at the GitHub, hopefully added it’s added soon.

**Comment by ItsMeGriff** [comment]
Closing due to it being a limitation in the plug-in itself
