### ISSUE TITLE
[BUG] Hub Vote Links

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#71]
**Describe the bug**
The "Vote" option from Fawnn The Guide in the /hub does not provide the vote link.

**To Reproduce**
1. Go to -40 56 21 coordinates in the /hub
2. Right-click the NPC, Fawnn The Guide
3. Click Vote

**Expected behavior**
A link to https://store.gorillocraft.com/vote displays in the chat.

**Screenshots**
![2022-07-20_23 58 30](https://user-images.githubusercontent.com/29812480/180150994-6994f468-00b7-4682-baa5-ead2d607febd.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Hub

**Comment by ImSnipper** [comment]
This is now fixed! Thanks for reporting.
