### ISSUE TITLE
[BUG] Player Warp 2 Purchase Notification

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#72]
**Describe the bug**
We received a report from a player named Angelay15 that when the second /playerwarp is purchased from /upgrades, they get the following notification:

"-1,000 Coins
You can not set 1 player warp!"

The player was charged the expected 2,500 coins, but the purchase notification message is inaccurate.

**To Reproduce**
1. Use /upgrades in survival
2. Purchase the first PlayerWarp
3. Purchase the second PlayerWarp

**Expected behavior**
The purchase notification states that 2,500 coins were deducted and that the player now has a second warp available.

**Screenshots**
![image](https://user-images.githubusercontent.com/29812480/180319841-38d1e073-85aa-423b-ac81-643286dcec62.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by ImSnipper** [comment]
This is now fixed!
