### ISSUE TITLE
[BUG] Battlepass Tier 32 Reward

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#73]
**Describe the bug**
The BattlePass Hoe from tier 32 is not rewarded upon claiming.

**To Reproduce**
1. Reach tier 32 in the /battlepass system
2. Claim the BattlePass Hoe from the premium rewards section
3. Check inventory

**Expected behavior**
Receive the Battlepass Hoe

**Screenshots**
![2022-07-21_17 45 21](https://user-images.githubusercontent.com/29812480/180339572-54beaef1-b07e-42eb-a789-1ebfef8f978b.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by ImSnipper** [comment]
This seems to be fixed now - just tested it! Thanks for reporting.
