### ISSUE TITLE
[BUG] BattlePass Tier 41 Reward

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#74]
**Describe the bug**
Claiming the BattlePass Chestplate after reaching Tier 41 does not reward the chestplate.

**To Reproduce**
1. Reach tier 41 in /bp
2. Claim the BattlePass Chestplate

**Expected behavior**
Receive the Chestplate after claiming.

**Screenshots**
![2022-07-23_15 08 51](https://user-images.githubusercontent.com/29812480/180624531-4f754a93-64c1-49c9-9c52-0f39db9719b9.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by ImSnipper** [comment]
Fixed! Good ole spelling error....Thanks for reporting!
