### ISSUE TITLE
[FEATURE] Duration In History

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#75]
**Please describe the feature you think should be implented**
Can we add the duration of any issued punishment commands to the /history display? It would be helpful to see previous mute/tempbans duration if they were issued for 1 minute or 1 week so we can adjust future issues as needed.
![image](https://user-images.githubusercontent.com/29812480/180671461-68ac54d1-d1d4-4efa-a9f2-421f48bbb01b.png)

**Comment by ImSnipper** [comment]
Added!

/history now shows the duration for bans, and mutes. I did however remove the line indicating the type of punishment, and ID, since the type of punishment is displayed in the first line, and we aren't currently using the punishment ID for anything.
