### ISSUE TITLE
[BUG] Renaming an equipement with Anvil doesn't work

### ISSUE THREAD

**Issue by TheSimzHelper** [GorilloCraft/Server#76]
**Describe the bug**
Renaming an equipement or gear with the Anvil doesn't work. On my end I've added mending to some leather boots.

**To Reproduce**
1. Place the gear on the Anvil
2. Put a custom name
3. You may or may not add an enchantment
4. Have enough XP
5. Pull out the new gear

**Expected behavior**
To have the modified name using the Anvil because I've used the XP requiered for adding the custom name. 
For me the name of the leather boots was : The_Simz snowy boots

**Server that is affected : Survival**

**Additional context**
None.

**Comment by MelodyMcKenna** [comment]
I tested this out and found that renaming doesn't work when applying an item/enchant book/ores. Renaming works if the anvil only renames the item and does not combine it with anything else.
I'll add a video in #s2-bug-reporting.

**Comment by ImSnipper** [comment]
I believe this is fixed now.

I am able to apply a book to an item, and rename the item. I can also put a regular item in the anvil, rename it, pull out the new gear, and the new name is showing.

Sorry for the delay in getting to this.
