### ISSUE TITLE
[FEATURE] could we reduce the chance of getting a blue whale in the fishing contest

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#77]
the blue whale is way to common for a legendary, especially as it gives between 500cm and 1000cm. 

![image](https://user-images.githubusercontent.com/42377455/180992770-6c4f9917-e2bd-4958-9dfc-f2bd61bff254.png)
![image](https://user-images.githubusercontent.com/42377455/180993008-b3839f17-3f9f-451b-b75c-9d2d91b7a1f8.png)

**Comment by ImSnipper** [comment]
This is a fair point, and something I have noticed as well...the legendary blue whale shouldn't be something that all players catch in every competition.

Hopefully, this adjustment helps. If not, please let me know!
