### ISSUE TITLE
[FEATURE] Disable Spawner Type Change

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#78]
**Please describe the feature you think should be implemented**
Players can use the spawn eggs obtained in the /battlepass on spawners to change their type. A cow spawn egg can be used on a zombie spawner to make a cow spawner. Can we please disable this feature?

I'll post a video of changing the spawner type in #s2-bug-reporting

**Comment by MelodyMcKenna** [comment]
If disabling the feature isn't possible, we can replace the spawn eggs in /battlepass with something else. Eddie proposed replacing them with coins.

**Comment by apexmag** [comment]
Also need to find a way to check current spawners for alterations as well

**Comment by ImSnipper** [comment]
Fixed!

Players can no longer change the type of spawner with a spawn egg.

WorldGuard Blacklist
