### ISSUE TITLE
Fishing Contest bugged (Again)

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#79]
The fishing contest is bugged again where it doesn't end after 10 minutes and there is no timer on the top of the screen to show when it ends. 

Just toss a rod into the water to get one of the custom fish for the contest. Stick around for more than 10mins and you see it doesn't end.

**Comment by ImSnipper** [comment]
It seems that the daily restart fixed the issue...will look into what specifically caused it...

If it happens again, please reopen this issue!
