### ISSUE TITLE
[BUG] Invisible mounts at spawn

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#8]
**Describe the bug**
some cosmetic mounts turn invisible at spawn like the spider mount or the dragon

**To Reproduce**
1. Spawn a mount

**Expected behavior**
Show the Mount and be able to ride it

**Screenshots**
![2022-06-30_19 53 13](https://user-images.githubusercontent.com/42377455/176756229-43ab8036-0538-446f-bbc8-7743f5389907.png)

Affects Survival

**Comment by ItsMeGriff** [comment]
I believe this is because mob spawning is off in the region so we need to find a work around for that

**Comment by ItsMeGriff** [comment]
Adding the global tag because this might be an issue outside of survival

**Comment by ImSnipper** [comment]
This is now fixed.

Had to enable "mob-spawning" in the spawn region to allow pets, and mounts to spawn. I tried to light up the spawn area best I could to prevent a bunch of hostile mobs from spawning. Regardless, mobs won't damage you in the spawn region, and explosions are disabled, so I think this should be fine.

Thanks for reporting.
