### ISSUE TITLE
BlockTrak Stopped counting

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#80]
The item used to track blocks mined for tools that you get from the Upgrade merchant is bugged. It stops counting blocks broken when you reach 2663 for the pickaxe. 

1.) Get the Thingy from /upgrades and slap it on a pick
2.) try to mine more than 2663 blocks
3.) See the number not go past it 2663.

**Comment by ImSnipper** [comment]
This is super odd......

Giz suggested that you try adding the BlockTrak item to your Pickaxe again. Let's give that a try, and see if it continues to track.
Once you buy it, I will refund your coins.

**Comment by EddieJ5** [comment]
Did this and it just added a new counter, I'll update if the new counter breaks or not.

**Comment by ImSnipper** [comment]
@ImGiz can you please look into this when you get the chance?

**Comment by MelodyMcKenna** [comment]
Hate to add to this, but the player kill count on my axe stopped at 9. Maybe it's linked to what Eddie is experiencing.

**Comment by ImSnipper** [comment]
This might be fixed at the daily restart (will need to test)

**Comment by ImSnipper** [comment]
No further response in the past 2 days - assuming the plugin update resolved this issue.

If not, please reopen this issue.
