### ISSUE TITLE
[BUG] clearing chat doesnt affect creative

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#81]
chat does not clear when in creative (might be due to me being in staffworld at the time)
![2022-07-30_14 37 56](https://user-images.githubusercontent.com/42377455/181917120-cf465b36-366b-4352-b379-bb59e9c1e8f7.png)

**Comment by ImSnipper** [comment]
This is most likely because you were in the staff world, which is immune to the punishment system.
