### ISSUE TITLE
[FEATURE] Unban/mute Reason Displayed In History

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#82]
**Please describe the feature you think should be implemented**
The 'reason' for unban/unmute to display in /history would be helpful to inform other staff members of why the decision to unban/unmute is made.

![image](https://user-images.githubusercontent.com/29812480/181936801-fdb39c3d-33cb-484f-a029-df7d66bcb953.png)

Unban reason: Sibling playing on the same IP as lukaq_
![image](https://user-images.githubusercontent.com/29812480/181936679-d12e5552-98a0-405d-a0ea-9338cdad2e71.png)

**Comment by ImSnipper** [comment]
Consider it done! 

If a player was unbanned, the reason is now displayed too.
