### ISSUE TITLE
[BUG] Diamond Helm Challenge

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#83]
**Describe the bug**
Enchanting a diamond helmet with protection 3 does not complete the week 4 premium challenge. I've tested on the enchant table and with a protection 3 book.

**To Reproduce**
1. Get a diamond helm
2. Use an enchanting table to enchant with protection 3 or:
3. Use a protection 3 enchanted book on the helmet with an anvil

**Expected behavior**
The /battlepass challenge completes.

**Screenshots**
![2022-07-30_15 17 54](https://user-images.githubusercontent.com/29812480/182001974-7375e0b1-138c-4d04-b483-06ba2eb1ef69.png)
![2022-07-30_15 18 12](https://user-images.githubusercontent.com/29812480/182001977-0b8faa64-b006-4730-bf00-84825a7e1fab.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by MelodyMcKenna** [comment]
It looks like the week 4 Another Upgrade challenge is also bugged. I used an enchanting table to apply Efficiency 3, and the challenge didn't complete.

**Comment by ImSnipper** [comment]
The diamond helmet challenge is fixed.

Working on the "Another Upgrade" challenge now.

**Comment by ImSnipper** [comment]
Both fixed! Tested as well.
