### ISSUE TITLE
[BUG] Tier 55 Battlepass Leggings

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#84]
**Describe the bug**
The Battlepass Leggings reward for tier 55 does not reward the leggings.

**To Reproduce**
1. Reach tier 55 in the /battlepass system
2. Claim the Battlepass Leggings

**Expected behavior**
Receive the Leggings after claiming them.

**Screenshots**
![2022-07-30_15 39 37](https://user-images.githubusercontent.com/29812480/182002482-ba53149b-bf16-4636-b590-87a3ad4b7b9f.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by ImSnipper** [comment]
Fixed! Was a capitalization issue.

I've added the BPLeggings to your inventory.
