### ISSUE TITLE
[BUG] WEEK 4 CHALLENGE: BANQUET (WORDING ISSUE MAYBE?)

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#85]
**Describe the bug**
Week 4 Challenge: Banquet description states "To complete this challenge, you must eat/consume 8 cakes." When attempting to complete this challenge, I only needed to eat 1 full cake and 1/4 of a second one. I assumed from the wording I needed to eat 8 full cakes.

**To Reproduce**
1. Make cakes to complete Banquet challenge (in Week 4 Module)
2. Eat cakes until challenge completes.

**Expected behavior**
You need to eat 8 FULL cakes to complete and earn points from Banquet challenge.

**Screenshots**
![2022-07-30_19 25 24](https://user-images.githubusercontent.com/109165139/182003572-21f4a1e0-ffac-4b8b-a582-a8c093c15468.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
When I mention wording in the title, I was think the easiest way to go about fixing the issue is rewording the challenge to '8 slices of cake' rather than '8 cakes'. Either this or changing the challenge to make it so you need to eat 8 full cakes to complete it so it matches the current wording.

**Comment by ImSnipper** [comment]
This is now fixed.

This challenge should require the player to eat 8 full cakes. Since there are 7 slices in each cake, I've set the required amount to 56 slices (or, 8 full cakes).
