### ISSUE TITLE
[BUG] Ban Duration In History

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#86]
**Describe the bug**
The /history command shows `Mute Duration` when the user was banned and `Ban Duration` when the user was muted.

**To Reproduce**
1. Ban a user
2. Check the user's /history
3. Mute a user
4. Check the user's /history

**Expected behavior**
The muted user's /history shows the mute duration and the banned user's /history shows the ban duration.

**Screenshots**
![image](https://user-images.githubusercontent.com/29812480/182071983-84fb96e3-e5b1-4c53-9dc0-dc1aa8882476.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Global

**Additional context**

**Comment by ImSnipper** [comment]
Fixed! Thanks for reporting.
