### ISSUE TITLE
[BUG] Mangrove Wood In Creative

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#87]
**Describe the bug**
Players do not have permission to use the item `Minecraft:mangrove_wood` in the Creative world.

**To Reproduce**
1. Join the creative world with /creative
2. Choose Mangrove Wood from the list.
3. Error message

**Expected behavior**
To have access to the Mangrove Wood block in /creative

**Screenshots**
![image](https://user-images.githubusercontent.com/29812480/182077213-8a4849ed-6f0f-4ece-8331-3c4f82e79801.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Creative

**Additional context**

**Comment by ImSnipper** [comment]
This will be fixed at the daily restart.
