### ISSUE TITLE
[BUG] BattlePass Tier 62 Pickaxe

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#88]
**Describe the bug**
Claiming the BattlePass Pickaxe does not reward the item.

**To Reproduce**
1. Reach Tier 62 on the /battlepass
2. Claim the BattlePass Pickaxe

**Expected behavior**
Receive the BattlePass Pickaxe after claiming from /bp.

**Screenshots**
![2022-07-31_23 45 36](https://user-images.githubusercontent.com/29812480/182088864-38058362-1a81-4a99-a927-35e06a27e9be.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**

**Comment by ImSnipper** [comment]
Fixed! Yet another annoying capitalization issue....

Let me know when you are next online so that I can give your reward!
