### ISSUE TITLE
[BUG] Player Warp Price

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#89]
**Describe the bug**
The price for the second player warp in /upgrades is different for me, username MelodyMcKenna, and Skee, username sk245802.

**To Reproduce**
1. See screenshots below

**Expected behavior**
Consistent prices for both player warps.

**Screenshots**
Screenshots for MelodyMcKenna:
![2022-08-02_13 41 10](https://user-images.githubusercontent.com/29812480/182470696-0af7fe9b-28ba-4c37-8029-28a3ebc28418.png)
![2022-08-02_13 41 12](https://user-images.githubusercontent.com/29812480/182470707-e1a75b6f-7788-41b8-a3a2-c132b6ea2cef.png)

Screenshots for sk245802:
![image](https://user-images.githubusercontent.com/29812480/182470833-8eecceb9-6b49-4fee-893a-73e438488212.png)
![image](https://user-images.githubusercontent.com/29812480/182470877-f495a56e-7961-41c6-ac61-5b7a56bc31ce.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
We're wondering if having it purchased is changing the displayed price.

**Comment by ImSnipper** [comment]
Fixed. The PW Upgrade II was taking 2,500 coins as expected, but was just displaying the incorrect amount once purchased.

Thanks for reporting.
