### ISSUE TITLE
[BUG] CHANGE THIS TITLE!!

### ISSUE THREAD

**Issue by EddieJ5** [GorilloCraft/Server#91]
Reaction games are starting to declare 2nd or third place people the winners. 

Kinda difficult to reproduce but a screenshot works fine 

![image](https://user-images.githubusercontent.com/109323715/182475093-60efb180-eeba-47a7-b4f7-88fceb12c804.png)

All servers are affected

**Comment by ImSnipper** [comment]
Not really sure why this would happen...

My guess is there was a lag spike and registered the wrong message. If this happens again, please reopen this issue.
