### ISSUE TITLE
[BUG] Helpers dont have access to world edit in StaffWorld

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#92]
**Describe the bug**
Helpers dont have access to world edit

comes up with this when i try
![image](https://user-images.githubusercontent.com/42377455/182483403-d117b81e-b708-4744-a236-884bb4379317.png)

**Comment by ImSnipper** [comment]
Hmm...I'm almost certain that world edit is working for moderators (and the moderator group is inheriting the world edit permissions from the helper group)...I believe Eddie is able to use it... Eddie, can you confirm?

Also, what command are you trying to run? @HagridHills

**Comment by HagridHills** [comment]
The command I used there was //brush sphere sand 2
I have been able to use the command in normal creative but not staffworld

**Comment by ImSnipper** [comment]
Thanks. Can you try again, please?

**Comment by HagridHills** [comment]
Will do in the morning

**Comment by HagridHills** [comment]
yup it works now, Thank you
