### ISSUE TITLE
[BUG] Personal Player Warp Menu: Toggle lock option

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#95]
**Describe the bug**
When trying to toggle lock for your own warp in the personal warp menu, it does not lock. Instead, it says "**Player Warp** >> That warp does not exist!"

**To Reproduce**
1. Go to player warps menu
2. Go to "My warps" menu
3. Click on any personal player warps
4. Click on door icon labeled "**Toggle Lock** Click to toggle lock on/off"

**Expected behavior**
It should toggle the player warp lock (I am assuming this is for locking access to the warp for other players?). 

**Screenshots**
Posted a video clip in #s2-bug-reporting channel in Discord.

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
N/A

**Comment by ImSnipper** [comment]
Fixed! Thanks for reporting
