### ISSUE TITLE
[BUG] Shopkeeper in Regular Survival World

### ISSUE THREAD

**Issue by foodbandit** [GorilloCraft/Server#96]
**Describe the bug**
You are able to set up a shopkeeper outside of the shop plot area, and it is functional. This is not supposed to be an option.

**To Reproduce**
1. Purchase shopkeeper egg from NPC in Shops area
2. Go to regular survival server and set up shopkeeper as normal
3. Do trade within shopkeeper after set up.

**Expected behavior**
To repeat. this is not meant to be an option within the normal survival world. Needs to be disabled in some way to prevent players from using it/placing it there.

**Screenshots**
Video capture in #s2-bug-reporting channel in Discord.

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Additional context**
I think it would be good to implement more shop plots soon, as there is hardly any space left in the actual shop plot area. This would help discourage people putting shopkeepers in regular survival as well while the issue is being resolved (this issue do be a bit more urgent).

**Comment by ImSnipper** [comment]
Fixed
