### ISSUE TITLE
[FEATURE] Armour stand arms

### ISSUE THREAD

**Issue by GorilloYT** [GorilloCraft/Server#97]
**Please describe the feature you think should be implemented**
Add a plugin that adds armour stand arms,

Here's one I found online: 
https://www.spigotmc.org/resources/armedarmorstands-automatically-add-arms-on-armor-stands.7098/

**Comment by ImSnipper** [comment]
Added!

By default, when a player places an armor stand, the armor stand will have arms. This feature can be toggled off with the `/togglearms` command
