### ISSUE TITLE
[FEATURE] /playtime

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#99]
**Please describe the feature you think should be implented**
could we have access to /playtime. Only the admins have access to it

**Comment by ImSnipper** [comment]
I've added `/playtime` as a command for all players on Creative, and Survival.

However, staff can do `/playtime <player>` to see the playtime of others.

Please note that these commands are specific to the server. Unfortunately, only admins/devs can see the global playtime through the stats page.

**Comment by HagridHills** [comment]
it comes up with this when i try using the command 

![image](https://user-images.githubusercontent.com/42377455/183216028-fb283cd2-bd8c-4270-9ea0-cb952517818c.png)

**Comment by EddieJ5** [comment]
> it comes up with this when i try using the command
> 
> ![image](https://user-images.githubusercontent.com/42377455/183216028-fb283cd2-bd8c-4270-9ea0-cb952517818c.png)

I have perms for Playtime in the Hub but not in the Survival or Creative/StaffWorld server.
